完善

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -6,29 +6,35 @@ on:
       - main
 
 jobs:
-  test:
+  build:
     runs-on: ubuntu-latest
-
-    services:
-      texlive:
-        image: latex-docker:latest
-        options: --entrypoint "/bin/sh"
-        ports:
-          - 4000:4000
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-
+    
     steps:
     - name: Checkout repository
-      uses: actions/checkout@v4
-
+      uses: actions/checkout@v2
+    
     - name: Set up Python
       uses: actions/setup-python@v2
       with:
-        python-version: 3.11
-
-    - name: Install rich library
-      run: pip install rich
-
-    - name: Run test.py
-      run: python test.py
+        python-version: '3.11'  # Specify the Python version you want to use
+      
+    - name: Check if TeX Live is installed
+      id: texlive-check
+      run: |
+        if ! command -v pdflatex &> /dev/null; then
+          echo "TeX Live not found, installing..."
+          sudo apt-get update
+          sudo apt-get install -y texlive-full
+          echo "TeX Live installed successfully."
+        else
+          echo "TeX Live is already installed."
+        fi
+    
+    - name: Install dependencies
+      run: |
+        python -m pip install --upgrade pip
+        pip install rich
+    
+    - name: Run tests
+      run: |
+        python tests/test.py
